import { Inter } from "next/font/google";
import Bottombar from "@/components/Bottombar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ekitab: Indias first online book store with mock testing.",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex h-dvh flex-col md:flex-row-reverse">
          <div className="grow md:w-0.5">{children}</div>
          <Bottombar></Bottombar>
        </div>
      </body>
    </html>
  );
}
